// See README.md for license details.

package axi2csb

import chisel3._

/**
  * This provides an alternate way to run tests, by executing then as a main
  * From sbt (Note: the test: prefix is because this main is under the test package hierarchy):
  */
object AXI2CSBMain extends App {
  iotesters.Driver.execute(args, () => new AXI2CSBUTWarpper) {
    c => new AXI2CSBUnitTester(c)
  }
}

/**
  * This provides a way to run the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  *
  */
object AXI2CSBRepl extends App {
  iotesters.Driver.executeFirrtlRepl(args, () => new AXI2CSB)
}
